# Generated by Django 4.0.1 on 2022-01-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='data',
            new_name='dia',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(choices=[('1', '07:00 ás 08:00'), ('2', '08:00 ás 09:00'), ('3', '09:00 ás 10:00'), ('4', '10:00 ás 11:00'), ('5', '11:00 ás 12:00')], max_length=10),
        ),
    ]
