# Generated by Django 4.0.1 on 2022-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_rename_data_agenda_dia_alter_agenda_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.DateField(help_text='Insira uma data para agenda'),
        ),
    ]
