# Generated by Django 4.0 on 2022-01-03 18:53

import django.core.validators
from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sexo', models.CharField(choices=[('MAS', 'Maculino'), ('FEM', 'Feminino')], max_length=9)),
                ('telefone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="O número precisa estar neste formato:                         '+99 99 9999-0000'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=50, unique=True, verbose_name='cnpj')),
            ],
        ),
    ]
