# Generated by Django 4.0.1 on 2022-01-11 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_consulta_agenda_alter_consulta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='clientes.cliente'),
        ),
    ]
